base: "https://wizley.io" # DO NOT INCLUDE "/" AT THE END.

author:
  name: "Wizley"
  github: "wizley9999"
  identities:
    - "Y.S. Lee"
    - "Software Developer"
  tagline: "A passionate Software Developer with a focus on cybersecurity."

giscus:
  repo: "[ENTER REPO HERE]"
  repoId: "[ENTER REPO ID HERE]"
  category: "[ENTER CATEGORY NAME HERE]"
  categoryId: "[ENTER CATEGORY ID HERE]"
  mapping: "pathname"
  reactionsEnabled: "1"
  inputPosition: "top"
  theme: "light"
  lang: "en"
